### ISSUE TITLE
Move josehbez/gp-tracking  to gnome-promodoro/gnome-pomodoro-tracking

### ISSUE THREAD

**Issue by josehbez** [gnome-pomodoro/gnome-pomodoro-tracking#12]
- [x] update repo name from gp-tracking to gnome-pomodoro-tracking 
- [x] update script startup.sh 
- [x] update readme.md 
- [x] Transfer repo
